heat_template_version: 2015-04-30

description: >
  HOT template to create a AliasIp:

parameters:
  name:
    type: string
    description: name for the AliasIp
    # required: optional
  fq_name:
    type: string
    description: fq_name for the AliasIp
    # required: optional
  alias_ip_address:
    type: string
    description: Alias ip address.
    # operations: CR
    # required: required
  alias_ip_address_family:
    type: string
    description: Ip address family of the alias ip, IpV4 or IpV6
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  project_refs:
    type: string
    description: Reference to project from which this alias ip was allocated.
    # required: optional
  virtual_machine_interface_refs:
    type: string
    description: Reference to virtual machine interface to which this alias ip is attached.
    # required: optional
  alias_ip_pool:
    type: string
    description: alias_ip_pool for the AliasIp
    # required: optional

resources:
  template_AliasIp:
    type: OS::ContrailV2::AliasIp
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      alias_ip_address: { get_param: alias_ip_address }
      alias_ip_address_family: { get_param: alias_ip_address_family }
      display_name: { get_param: display_name }
      project_refs: [{ get_param: project_refs }]
      virtual_machine_interface_refs: [{ get_param: virtual_machine_interface_refs }]
      alias_ip_pool: { get_param: alias_ip_pool }

