heat_template_version: 2015-04-30

description: >
  HOT template to create a LoadbalancerMember:

parameters:
  name:
    type: string
    description: name for the LoadbalancerMember
    # required: optional
  fq_name:
    type: string
    description: fq_name for the LoadbalancerMember
    # required: optional
  loadbalancer_member_properties_admin_state:
    type: boolean
    description: admin_state for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  loadbalancer_member_properties_status:
    type: string
    description: status for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  loadbalancer_member_properties_status_description:
    type: string
    description: status_description for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  loadbalancer_member_properties_protocol_port:
    type: number
    description: protocol_port for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  loadbalancer_member_properties_weight:
    type: number
    description: weight for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  loadbalancer_member_properties_address:
    type: string
    description: address for the LoadbalancerMember
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  loadbalancer_pool:
    type: string
    description: loadbalancer_pool for the LoadbalancerMember
    # required: optional

resources:
  template_LoadbalancerMember:
    type: OS::ContrailV2::LoadbalancerMember
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      loadbalancer_member_properties:
        {
          loadbalancer_member_properties_admin_state: { get_param: loadbalancer_member_properties_admin_state },
          loadbalancer_member_properties_status: { get_param: loadbalancer_member_properties_status },
          loadbalancer_member_properties_status_description: { get_param: loadbalancer_member_properties_status_description },
          loadbalancer_member_properties_protocol_port: { get_param: loadbalancer_member_properties_protocol_port },
          loadbalancer_member_properties_weight: { get_param: loadbalancer_member_properties_weight },
          loadbalancer_member_properties_address: { get_param: loadbalancer_member_properties_address },
        }
      display_name: { get_param: display_name }
      loadbalancer_pool: { get_param: loadbalancer_pool }

