heat_template_version: 2015-04-30

description: >
  HOT template to create a Loadbalancer:

parameters:
  name:
    type: string
    description: name for the Loadbalancer
    # required: optional
  fq_name:
    type: string
    description: fq_name for the Loadbalancer
    # required: optional
  loadbalancer_properties_status:
    type: string
    description: status for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_properties_provisioning_status:
    type: string
    description: provisioning_status for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_properties_operating_status:
    type: string
    description: operating_status for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_properties_vip_subnet_id:
    type: string
    description: vip_subnet_id for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_properties_vip_address:
    type: string
    description: vip_address for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_properties_admin_state:
    type: boolean
    description: admin_state for the Loadbalancer
    # operations: CRUD
    # required: optional
  loadbalancer_provider:
    type: string
    description: loadbalancer_provider for the Loadbalancer
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  service_instance_refs:
    type: string
    description: service_instance_refs for the Loadbalancer
    # required: optional
  virtual_machine_interface_refs:
    type: string
    description: virtual_machine_interface_refs for the Loadbalancer
    # required: optional
  project:
    type: string
    description: project for the Loadbalancer
    # required: optional

resources:
  template_Loadbalancer:
    type: OS::ContrailV2::Loadbalancer
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      loadbalancer_properties:
        {
          loadbalancer_properties_status: { get_param: loadbalancer_properties_status },
          loadbalancer_properties_provisioning_status: { get_param: loadbalancer_properties_provisioning_status },
          loadbalancer_properties_operating_status: { get_param: loadbalancer_properties_operating_status },
          loadbalancer_properties_vip_subnet_id: { get_param: loadbalancer_properties_vip_subnet_id },
          loadbalancer_properties_vip_address: { get_param: loadbalancer_properties_vip_address },
          loadbalancer_properties_admin_state: { get_param: loadbalancer_properties_admin_state },
        }
      loadbalancer_provider: { get_param: loadbalancer_provider }
      display_name: { get_param: display_name }
      service_instance_refs: [{ get_param: service_instance_refs }]
      virtual_machine_interface_refs: [{ get_param: virtual_machine_interface_refs }]
      project: { get_param: project }

