heat_template_version: 2015-04-30

description: >
  HOT template to create a NetworkIpam:

parameters:
  name:
    type: string
    description: name for the NetworkIpam
    # required: optional
  fq_name:
    type: string
    description: fq_name for the NetworkIpam
    # required: optional
  network_ipam_mgmt_ipam_method:
    type: string
    description: ipam_method for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_method:
    type: string
    description: ipam_dns_method for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address:
    type: string
    description: ip_address for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name:
    type: string
    description: In case of virtual DNS server, name of virtual DNS server
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name:
    type: string
    description: Name of the DHCP option
    # operations: CRUD
    # required: true
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value:
    type: string
    description: Encoded DHCP option value (decimal)
    # operations: CRUD
    # required: true
  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes:
    type: string
    description: Value of the DHCP option to be copied byte by byte
    # operations: CRUD
    # required: true
  network_ipam_mgmt_cidr_block_ip_prefix:
    type: string
    description: ip_prefix for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_cidr_block_ip_prefix_len:
    type: number
    description: ip_prefix_len for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_prefix:
    type: string
    description: Ip prefix/len format prefix
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_next_hop:
    type: string
    description: Ip address or service instance name.
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_next_hop_type:
    type: string
    description: next_hop_type for the NetworkIpam
    # operations: CRUD
    # required: optional
  network_ipam_mgmt_host_routes_route_community_attributes_community_attribute:
    type: string
    description: community_attribute for the NetworkIpam
    # operations: CRUD
    # required: optional
  display_name:
    type: string
    description: Display name user configured string(name) that can be updated any time. Used as openstack name.
    # operations: CRUD
    # required: optional
  virtual_DNS_refs:
    type: string
    description: Reference to virtual DNS used by this IPAM.
    # required: optional
  project:
    type: string
    description: project for the NetworkIpam
    # required: optional

resources:
  template_NetworkIpam:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: { get_param: name }
      fq_name: { get_param: fq_name }
      network_ipam_mgmt:
        {
          network_ipam_mgmt_ipam_method: { get_param: network_ipam_mgmt_ipam_method },
          network_ipam_mgmt_ipam_dns_method: { get_param: network_ipam_mgmt_ipam_dns_method },
          network_ipam_mgmt_ipam_dns_server:
            {
              network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address:
                {
                  network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address: [{ get_param: network_ipam_mgmt_ipam_dns_server_tenant_dns_server_address_ip_address }],
                },
              network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name: { get_param: network_ipam_mgmt_ipam_dns_server_virtual_dns_server_name },
            },
          network_ipam_mgmt_dhcp_option_list:
            {
              network_ipam_mgmt_dhcp_option_list_dhcp_option:
                [{
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_name },
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value },
                  network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes: { get_param: network_ipam_mgmt_dhcp_option_list_dhcp_option_dhcp_option_value_bytes },
                }],
            },
          network_ipam_mgmt_cidr_block:
            {
              network_ipam_mgmt_cidr_block_ip_prefix: { get_param: network_ipam_mgmt_cidr_block_ip_prefix },
              network_ipam_mgmt_cidr_block_ip_prefix_len: { get_param: network_ipam_mgmt_cidr_block_ip_prefix_len },
            },
          network_ipam_mgmt_host_routes:
            {
              network_ipam_mgmt_host_routes_route:
                [{
                  network_ipam_mgmt_host_routes_route_prefix: { get_param: network_ipam_mgmt_host_routes_route_prefix },
                  network_ipam_mgmt_host_routes_route_next_hop: { get_param: network_ipam_mgmt_host_routes_route_next_hop },
                  network_ipam_mgmt_host_routes_route_next_hop_type: { get_param: network_ipam_mgmt_host_routes_route_next_hop_type },
                  network_ipam_mgmt_host_routes_route_community_attributes:
                    {
                      network_ipam_mgmt_host_routes_route_community_attributes_community_attribute: [{ get_param: network_ipam_mgmt_host_routes_route_community_attributes_community_attribute }],
                    },
                }],
            },
        }
      display_name: { get_param: display_name }
      virtual_DNS_refs: [{ get_param: virtual_DNS_refs }]
      project: { get_param: project }

