heat_template_version: 2015-04-30

description: >
  HOT template to creates a virtual network with one subnet each. 
  set allow-transit, forwarding_mode and route-targets

parameters:
  private_net_1_name:
    type: string
    description: Name of private network to be created
  private_net_1_prefix:
    type: string
    description: Private network address prefix
  private_net_1_prefix_len:
    type: string
    description: Private network address prefix len
  allow_transit:
    type: boolean
    description: Private network allow transit
  forwarding_mode:
    type: string
    description: Private network forwarding_mode
  route_target_1:
    type: string
    description: Private network route-target
  route_target_2:
    type: string
    description: Private network route-target
  project_fqdn:
    type: string
    description: Project where we create the virtual-network

resources:
  template_NetworkIpam_1:
    type: OS::Contrail::NetworkIpam
    properties:
      name: { get_param: private_net_1_name }

  template_VirtualNetwork_1:
    type: OS::Contrail::VirtualNetwork
    depends_on: [ template_NetworkIpam_1 ]
    properties:
      name: { get_param: private_net_1_name }
      virtual_network_properties:
        {
          virtual_network_properties_allow_transit: { get_param: allow_transit },
          virtual_network_properties_forwarding_mode: { get_param: forwarding_mode },
        }
      route_target_list:
        {
          route_target_list_route_target: [{ get_param: route_target_1 }, { get_param: route_target_2 }],
        }
      network_ipam_refs: [{ get_resource: template_NetworkIpam_1 }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: private_net_1_prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: private_net_1_prefix_len },
                },
            }]
         }]
      project: { get_param: project_fqdn }

