heat_template_version: 2013-05-23

parameters:
  network1:
    type: string
    description: Name of management network to be created
  network2:
    type: string
    description: Name of left network to be created
  network3:
    type: string
    description: Name of right network to be created
  image:
    type: string
    description: Name of the image
  flavor:
    type: string
    description: Flavor
  service_instance_name:
    type: string
    label: Service instance fq name
    description: Service instance for port tuple

resources:
  port_1:
    type: "OS::Neutron::Port"
    properties:
      admin_state_up: true
      network: { get_param: network1 }

  port_2:
    type: "OS::Neutron::Port"
    properties:
      admin_state_up: true
      network: { get_param: network2 }

  port_3:
    type: "OS::Neutron::Port"
    properties:
      admin_state_up: true
      network: { get_param: network3 }

  instance:
    type: OS::Nova::Server
    properties:
      name: 
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: port_1 }
        - port: { get_resource: port_2 }
        - port: { get_resource: port_3 }

  port_tuple:
    type: OS::Contrail::PortTuple
    depends_on: [ instance, port_1, port_2, port_3 ]
    properties:
      name: { get_attr: [instance, name] } 
      service_instance: { get_param: service_instance_name } 
      ports: [
        { get_resource: port_1 },
        { get_resource: port_2 },
        { get_resource: port_3 }
      ]
