heat_template_version: 2013-05-23

parameters:
  service_template_name:
    type: string
    label: Service template fq name
    description: Service template for port tuple
  service_version:
    type: string
    description: Indicates service version
  service_mode:
    type: string
    description: service mode
  service_type:
    type: string
    description: service type
  service_image:
    type: string
    description: Name of the image
  service_flavor:
    type: string
    description: Flavor
  service_interface_type_list:
    type: string
    description: List of interface types
  service_ordered_interfaces:
    type: string
    description: Indicates service interfaces are ordered
  service_shared_ip_list:
    type: string
    description: List of shared ip enabled-disabled
  service_static_routes_list:
    type: string
    description: List of static routes enabled-disabled
  service_scaling:
    type: string
    description: Indicates whether service scaling is enabled
  service_availability_zone:
    type: string
    description: Indicates availability zone is enabled
  service_virtualization_type:
    type: string
    description: Indicates virtualization type

  service_instance_name:
    type: string
    label: Service instance fq name
    description: Service instance for port tuple
  management_network:
    type: string
    description: Name of management network to be created
  left_network:
    type: string
    description: Name of left network to be created
  right_network:
    type: string
    description: Name of right network to be created

  route_tag_1:
    type: string
    description: Tag for route table
  route_list_1:
    type: comma_delimited_list
    description: List of routes

  health_tag_1:
    type: string
    description: Tag for healt check
  health_1_enabled:
    type: boolean
    description: Health check enabled
  health_1_type:
    type: string
    description: Health check type
  health_1_delay:
    type: number
    description: Health check delay
  health_1_timeout:
    type: number
    description: Health check timeout
  health_1_retries:
    type: number
    description: Health check retries

resources:
  service_template:
    type: OS::Contrail::ServiceTemplate
    properties:
      name: { get_param: service_template_name }
      service_version: { get_param: service_version }
      service_mode: { get_param: service_mode }
      service_type: { get_param: service_type }
      image_name: { get_param: service_image }
      ordered_interfaces: { get_param: service_ordered_interfaces }
      flavor: { get_param: service_flavor }
      service_interface_type_list: { "Fn::Split" : [ ",", Ref: service_interface_type_list ] }
      service_scaling: { get_param: service_scaling }
      availability_zone_enable: { get_param: service_availability_zone }
      shared_ip_list: { "Fn::Split" : [ ",", Ref: service_shared_ip_list ] }
      static_routes_list: { "Fn::Split" : [ ",", Ref: service_static_routes_list ] }
      service_virtualization_type: { get_param: service_virtualization_type }

  service_instance:
    type: OS::Contrail::ServiceInstance
    properties:
      name: { get_param: service_instance_name }
      service_template: { get_resource:  service_template }
      interface_list: [
        { virtual_network: {get_param: management_network} },
        { virtual_network: {get_param: left_network} },
        { virtual_network: {get_param: right_network} }
      ]

  route_table_1:
    type: OS::Contrail::RouteTable
    depends_on: [ service_instance ]
    properties:
      name: { get_param: route_tag_1 }
      service_instance: { get_param: service_instance_name }
      service_port_tag: { get_param: route_tag_1 }
      routes: { get_param: route_list_1 }

  health_check_1:
    type: OS::Contrail::ServiceHealthCheck
    depends_on: [ service_instance ]
    properties:
      name: { get_param: health_tag_1 } 
      service_instance: { get_param: service_instance_name } 
      service_port_tag: { get_param: health_tag_1 } 
      monitor_type: { get_param: health_1_type } 
      delay: { get_param: health_1_delay } 
      timeout: { get_param: health_1_timeout } 
      max_retries: { get_param: health_1_retries } 
      enabled: { get_param: health_1_enabled } 

  instance_group:
    type: OS::Heat::AutoScalingGroup
    properties:
      desired_capacity: 2
      max_size: 5
      min_size: 1
      resource:
        type: port_tuple.yaml
        properties:
          image: { get_param: service_image }
          flavor: { get_param: service_flavor }
          network1: { get_param: management_network }
          network2: { get_param: left_network }
          network3: { get_param: right_network }
          service_instance_name: { get_param: service_instance_name }
