heat_template_version: 2013-05-23

description: >
  HOT template to creates a virtual machine interface

parameters:
  net_name:
    type: string
    description: Name of virtual network to be created
  shared:
    type: string
    description: Is virtual network shared
  external:
    type: string
    description: Is virtual network external
  forwarding_mode:
    type: string
    description: forwarding mode of the virtual network
  flood_unknown_unicast:
    type: string
    description: forwarding mode of the virtual network
  port_name:
    type: string
    label: Service port fq name
    description: Service port 1 for port tuple

resources:
  private_net:
    type: OS::Contrail::VirtualNetwork
    properties:
      name: { get_param: net_name }
      shared: { get_param: shared }
      external: { get_param: external }
      forwarding_mode: { get_param: forwarding_mode }
      flood_unknown_unicast: { get_param: flood_unknown_unicast }

  private_port_1:
    type: "OS::Contrail::VirtualMachineInterface"
    properties:
      name: { get_param: port_name }
      virtual_networks: [{ get_resource: private_net}]
