heat_template_version: 2013-05-23

description: >
  HOT template to creates an ipam

parameters:
  ipam_name:
    type: string
    description: Name of IPAM to be created

resources:
  ipam:
    type: OS::Contrail::NetworkIpam
    properties:
      name: { get_param: ipam_name }
