heat_template_version: 2013-05-23

description: >
  HOT template to create a service template for analyzer

parameters:
  name:
    type: string
    description: Name of service template
  mode:
    type: string
    description: service mode
  type:
    type: string
    description: service type
  image:
    type: string
    description: Name of the image
  service_interface_type_list:
    type: string
    description: List of interface types

resources:
  service_template:
    type: OS::Contrail::ServiceTemplate
    properties:
      name: { get_param: name }
      service_mode: { get_param: mode }
      service_type: { get_param: type }
      image_name: { get_param: image }
      service_interface_type_list: { "Fn::Split" : [ ",", Ref: service_interface_type_list ] }

outputs:
  service_template_fq_name:
    description: FQ name of the service template
    value: { get_attr: [ service_template, fq_name] }
